CREATE TABLE USERS (
	ID SERIAL PRIMARY KEY,
	LOGIN VARCHAR(256),
	PASSWORD VARCHAR(256),
	NAME VARCHAR(256),
	MAIL VARCHAR(256)
);

INSERT INTO USERS (LOGIN, PASSWORD, NAME, MAIL) VALUES ('fbar', 'fbar', 'Foo Bar', 'fbar@foo.bar');
